name: Hello
on:
  workflow_dispatch:
jobs:
    hello:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Hello world"
        - uses: actions/checkout@v4
        - name: set up python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'
        - name: Run python file
          run: python training/hello.py
