name: Hello
on:
  workflow_dispatch:
env:
  EXECUTION_ROLE_ARN: arn:aws:iam::764192796407:role/ads-test-executionrole
jobs:
    hello:
      runs-on: ubuntu-latest
      steps:
        #- run: echo "Hello world"
        - name: Install dependencies
          run: |
            pip install sagemaker  # SageMaker SDKのインストール
        - uses: actions/checkout@v4
        - name: set up python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'
        - name: Run python file
          run: python training/hello.py
